<?php
/**
 * @todo Initialise the view
 */
$this->headTitle($title);
?>
<p class="login-box-msg">Sign up to create an account</p>

<?php  $form = $signupForm; ?>
<?php $form->prepare(); ?>

<?php
/**
 * @todo If wrong CSRF token
 */
if($formErrors && array_key_exists('csrf', $formErrors))
{
	echo $this->formElementErrors()
		->setMessageOpenFormat('<label class="text-danger">')
		->setMessageSeparatorString('</label><label  class="text-danger">')
		->setMessageCloseString('</label>')
		->render($form->get('csrf'));
}
?>

<?php echo $this->form()->openTag($form)?>

	<div class="form-group has-feedback <?php echo count($form->get('userName')->getMessages()) > 0 ? 'has-error' : '' ?>">
		<?php echo $this->formelement($form->get('userName'))?>
		<?php
			echo $this->formElementErrors()
			    ->setMessageOpenFormat('<label class="text-danger">')
			    ->setMessageSeparatorString('</label><label  class="text-danger">')
			    ->setMessageCloseString('</label>')
			    ->render($form->get('userName'));
		?>
	</div>

	<div class="form-group has-feedback <?php echo count($form->get('userPassword')->getMessages()) > 0 ? 'has-error' : '' ?>">
		<?php echo $this->formelement($form->get('userPassword'))?>
		<?php
			echo $this->formElementErrors()
			    ->setMessageOpenFormat('<label class="text-danger">')
			    ->setMessageSeparatorString('</label><label  class="text-danger">')
			    ->setMessageCloseString('</label>')
			    ->render($form->get('userPassword'));
		?>
	</div>

	<div class="form-group has-feedback <?php echo count($form->get('userConfirmPassword')->getMessages()) > 0 ? 'has-error' : '' ?>">
		<?php echo $this->formelement($form->get('userConfirmPassword'))?>
		<?php
			echo $this->formElementErrors()
			    ->setMessageOpenFormat('<label class="text-danger">')
			    ->setMessageSeparatorString('</label><label  class="text-danger">')
			    ->setMessageCloseString('</label>')
			    ->render($form->get('userConfirmPassword'));
		?>
	</div>

	<div class="form-group has-feedback <?php echo count($form->get('userDateofBirth')->getMessages()) > 0 ? 'has-error' : '' ?>">
		<?php echo $this->formelement($form->get('userDateofBirth'))?>
		<?php
			echo $this->formElementErrors()
			    ->setMessageOpenFormat('<label class="text-danger">')
			    ->setMessageSeparatorString('</label><label  class="text-danger">')
			    ->setMessageCloseString('</label>')
			    ->render($form->get('userDateofBirth'));
		?>
	</div>

	<div class="form-group has-feedback <?php echo count($form->get('userPhoneNumber')->getMessages()) > 0 ? 'has-error' : '' ?>">
		<?php echo $this->formelement($form->get('userPhoneNumber'))?>
		<?php
			echo $this->formElementErrors()
			    ->setMessageOpenFormat('<label class="text-danger">')
			    ->setMessageSeparatorString('</label><label  class="text-danger">')
			    ->setMessageCloseString('</label>')
			    ->render($form->get('userPhoneNumber'));
		?>
	</div>

	<div class="form-group has-feedback <?php echo count($form->get('userAddress')->getMessages()) > 0 ? 'has-error' : '' ?>">
		<?php echo $this->formelement($form->get('userAddress'))?>
		<?php
			echo $this->formElementErrors()
			    ->setMessageOpenFormat('<label class="text-danger">')
			    ->setMessageSeparatorString('</label><label  class="text-danger">')
			    ->setMessageCloseString('</label>')
			    ->render($form->get('userAddress'));
		?>
	</div>

	<div class="form-group has-feedback <?php echo count($form->get('captcha')->getMessages()) > 0 ? 'has-error' : '' ?>">
		<?php echo $this->formelement($form->get('captcha'))?>
		<?php
			echo $this->formElementErrors()
			    ->setMessageOpenFormat('<label class="text-danger">')
			    ->setMessageSeparatorString('</label><label  class="text-danger">')
			    ->setMessageCloseString('</label>')
			    ->render($form->get('captcha'));
		?>
	</div>

	<div class="row">
		<div class="col-xs-8">

		</div>
		<!-- /.col -->
		<div class="col-xs-4 text-right">
			<?php echo $this->formElement($form->get('csrf')); ?>
			<?php echo $this->formElement($form->get('submit')); ?>
		</div>
		<!-- /.col -->
	</div>
<?php echo $this->form()->closeTag()?>
